"""stringtool_simple chat: minimal LLM-driven demo.

Runs `stringtool_simple` (reverse only) via the OpenAI Responses API.
One tool, one system prompt, one loop. Intended as a teaching example.

Requires the `openai` package and OPENAI_API_KEY in the environment.
"""

import json
import os
import subprocess
import sys
from pathlib import Path
from openai import OpenAI

MODEL = "gpt-5.6-luna"
BINARY = Path(__file__).resolve().parent / "dist" / ("stringtool_simple.exe" if os.name == "nt" else "stringtool_simple")

SYSTEM_PROMPT = (
    "You can call string tools to inspect or transform text. Tool results "
    "come back as JSON with a 'result' field. If you are asked to manipulate "
    "a string or a sequence of words then only respond with the answer "
    "generated by a tool - never answer from your own knowledge."
)

REVERSE_TOOL = {
    "type": "function",
    "name": "reverse",
    "description": "Reverse the characters in a string.",
    "parameters": {
        "type": "object",
        "properties": {
            "s": {"type": "string", "description": "The string to reverse."}
        },
        "required": ["s"],
        "additionalProperties": False,
    },
}


def main() -> None:
    client = OpenAI()
    prev_id = None
    print("stringtool_simple chat (blank or Ctrl-C to quit)\n")

    while True:
        try:
            user = input("you> ").strip()
        except (EOFError, KeyboardInterrupt):
            print(); break
        if not user:
            break
        new = [{"role": "user", "content": user}]

        while True:
            resp = client.responses.create(
                model=MODEL,
                input=new,
                previous_response_id=prev_id,
                instructions=SYSTEM_PROMPT,
                tools=[REVERSE_TOOL],
                reasoning={"effort": "low"},
            )
            prev_id = resp.id

            fcs = [it for it in resp.output if it.type == "function_call"]
            if not fcs:
                if resp.output_text:
                    print(f"\nassistant> {resp.output_text}\n")
                break

            new = []
            for fc in fcs:
                print(f"  [tool call] {fc.name} {fc.arguments}", file=sys.stderr)
                s = json.loads(fc.arguments)["s"]
                r = subprocess.run([str(BINARY), "reverse", s],
                                   capture_output=True, text=True)
                result = r.stdout.strip() if r.returncode == 0 else f"error: {r.stderr.strip()}"
                print(f"  [tool result] {result}", file=sys.stderr)
                new.append({
                    "type": "function_call_output",
                    "call_id": fc.call_id,
                    "output": result,
                })


if __name__ == "__main__":
    main()