"""Interactive chat that exposes stringtool to an OpenAI Responses-API model.

The OpenAI tools are sourced at startup by shelling out to the built
`dist/stringtool.exe schema` (or `stringtool` on non-Windows). Whenever the
model invokes one of those tools, we pipe its arguments JSON to
`stringtool.exe <op> -` on stdin and feed the JSON result back to the model
as a function_call_output item.

This uses the Responses API (/v1/responses) so that reasoning (thinking) can
coexist with function tools — Chat Completions only allows reasoning_effort
"none" for tools on gpt-5.6-luna. Reasoning items returned by the model are
preserved in the running input list so the model can continue its chain of
thought across tool calls.

Set the model with --model (default: gpt-5.6-luna). Set the binary path with
--bin; otherwise we look next to this script and in ./dist.

Requires the `openai` package and OPENAI_API_KEY in the environment.
"""

import json
import logging
import os
import subprocess
import sys
from pathlib import Path

from openai import OpenAI

log = logging.getLogger("chat")

DEFAULT_SYSTEM_PROMPT = (
    "You can call string tools to inspect or transform text. Tool results "
    "come back as JSON with a 'result' field. If you are asked to manipulate "
    "a string or a sequence of words then only respond with the answer "
    "generated by a tool — never answer from your own knowledge."
)


def default_bin() -> Path:
    here = Path(__file__).resolve().parent
    candidates = [
        here / "dist" / ("stringtool.exe" if os.name == "nt" else "stringtool"),
        here / ("stringtool.exe" if os.name == "nt" else "stringtool"),
    ]
    for c in candidates:
        if c.exists():
            return c
    raise SystemExit(f"stringtool binary not found near {here}; build it first or pass --bin.")


def load_tools(binary: Path) -> list[dict]:
    """Run `stringtool schema` and return the OpenAI tool list.

    `stringtool schema` emits the Chat-Completions tool shape
    ({"type":"function","function":{...}}); we convert to the flat Responses
    shape ({"type":"function","name":...,"parameters":...}) for the Responses API.
    """
    out = subprocess.run(
        [str(binary), "schema"],
        capture_output=True, text=True, check=True,
    )
    chat_tools = json.loads(out.stdout)
    resp_tools = []
    for t in chat_tools:
        if isinstance(t, dict) and "function" in t:
            f = t["function"]
            rt = {"type": "function", "name": f["name"],
                  "parameters": f.get("parameters", {"type": "object", "properties": {}})}
            if "description" in f:
                rt["description"] = f["description"]
            resp_tools.append(rt)
        else:
            resp_tools.append(t)
    return resp_tools


def call_tool(binary: Path, name: str, args_json: str) -> str:
    """Invoke `stringtool <name> -` with args_json on stdin; return its stdout."""
    argv = [str(binary), name, "-"]
    log.info("[server] exec %s", argv)
    log.debug("[server] stdin: %s", args_json)
    proc = subprocess.run(
        argv, input=args_json, capture_output=True, text=True,
    )
    log.debug("[server] returncode=%d", proc.returncode)
    log.debug("[server] stdout: %s", proc.stdout.strip())
    if proc.stderr:
        log.debug("[server] stderr: %s", proc.stderr.strip())
    if proc.returncode != 0:
        return json.dumps({"error": proc.stderr.strip(), "returncode": proc.returncode})
    return proc.stdout.strip()


def main() -> None:
    import argparse
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--model", default="gpt-5.6-luna",
                   help="OpenAI model id (default: gpt-5.6-luna)")
    p.add_argument("--bin", type=Path, default=None,
                   help="path to the stringtool binary (default: auto-detect)")
    p.add_argument("--verbose", "-v", action="store_true",
                   help="log tool-calling steps (client requests and server calls)")
    p.add_argument("--debug", action="store_true",
                   help="even more verbose (dump full input and output objects)")
    p.add_argument("--system-prompt", "--system", default=None,
                   help="override the system prompt (default: force tool use for string ops)")
    p.add_argument("--tool-choice", default="auto",
                   help="OpenAI tool_choice value (default: auto)")
    p.add_argument("--reasoning-effort", default="low",
                   choices=["none", "minimal", "low", "medium", "high", "xhigh", "max"],
                   help="reasoning effort (default: low; gpt-5.6-luna prefers low/medium)")
    p.add_argument("--reasoning-mode", default=None,
                   choices=["standard", "pro"],
                   help="reasoning mode (default: omit = standard; 'pro' may not be "
                        "supported on gpt-5.6-luna)")
    p.add_argument("--reasoning-summary", default="none",
                   choices=["none", "auto", "detailed", "concise"],
                   help="request a reasoning summary to log (default: none; 'auto' may "
                        "require org verification)")
    p.add_argument("--reasoning-context", default="auto",
                   choices=["auto", "current_turn", "all_turns"],
                   help="reasoning continuity across turns (default: auto)")
    args = p.parse_args()

    level = logging.DEBUG if args.debug else logging.INFO if args.verbose else logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(asctime)s %(levelname)-5s %(message)s",
        datefmt="%H:%M:%S",
        stream=sys.stderr,
    )

    binary = args.bin or default_bin()
    tools = load_tools(binary)
    log.info("loaded %d tools from %s (Responses-API shape)", len(tools), binary)
    print(f"[loaded {len(tools)} tools from {binary}]", file=sys.stderr)
    log.debug("tools: %s", json.dumps(tools))

    system_prompt = args.system_prompt if args.system_prompt is not None else DEFAULT_SYSTEM_PROMPT
    log.info("system prompt (len=%d): %s", len(system_prompt), system_prompt)
    log.info("reasoning: effort=%s mode=%s summary=%s",
             args.reasoning_effort, args.reasoning_mode or "(omitted)", args.reasoning_summary)

    reasoning = {"effort": args.reasoning_effort}
    if args.reasoning_mode:
        reasoning["mode"] = args.reasoning_mode
    if args.reasoning_summary != "none":
        reasoning["summary"] = args.reasoning_summary
    reasoning["context"] = args.reasoning_context

    client = OpenAI()
    print("stringtool chat (Responses API; type your message; blank line or Ctrl-C to quit)\n")

    last_response_id: str | None = None

    while True:
        try:
            user = input("you> ").strip()
        except (EOFError, KeyboardInterrupt):
            print(); break
        if not user:
            break
        new_items: list[dict] = [{"role": "user", "content": user}]

        turn = 0
        while True:
            turn += 1
            log.info("[client] POST /v1/responses model=%s turn=%d n_new=%d prev_id=%s",
                     args.model, turn, len(new_items), last_response_id or "(none)")
            log.debug("[client] input items: %s", json.dumps(new_items))

            resp = client.responses.create(
                model=args.model,
                input=new_items,
                previous_response_id=last_response_id,
                instructions=system_prompt,
                tools=tools,
                tool_choice=args.tool_choice,
                reasoning=reasoning,
            )
            last_response_id = resp.id
            log.debug("[client] response: %s", resp.model_dump_json())

            for item in resp.output:
                if getattr(item, "type", None) == "reasoning":
                    summaries = getattr(item, "summary", None) or []
                    for s in summaries:
                        text = getattr(s, "text", "")
                        if text:
                            print(f"  [thinking] {text}", file=sys.stderr)

            func_calls = [it for it in resp.output
                          if getattr(it, "type", None) == "function_call"]

            if not func_calls:
                text = resp.output_text or ""
                if text:
                    print(f"\nassistant> {text}\n")
                else:
                    log.info("[assistant] (no final text, no tool calls)")
                break

            new_items = []
            for fc in func_calls:
                name = fc.name
                args_json = fc.arguments or "{}"
                log.info("[client] model invoked tool: %s args=%s call_id=%s",
                         name, args_json, fc.call_id)
                print(f"  [tool call] {name} {args_json}", file=sys.stderr)
                result = call_tool(binary, name, args_json)
                print(f"  [tool result] {result}", file=sys.stderr)
                new_items.append({
                    "type": "function_call_output",
                    "call_id": fc.call_id,
                    "output": result,
                })


if __name__ == "__main__":
    main()